services:
  linteum-db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    networks:
      - linteum_prod1
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  linteum-api:
    build:
      context: .
      dockerfile: Linteum.Api/Dockerfile
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    environment:
      - ConnectionStrings__DefaultConnection=Host=${DB_CONTAINER_NAME};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - MASTER_PASSWORD=${MASTER_PASSWORD}
      - MASTER_USER=${MASTER_USER}
      - MASTER_EMAIL=${MASTER_EMAIL}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ASPNETCORE_URLS=http://*:${API_CONTAINER_PORT}
      - CorsOrigins__0=http://localhost:${BLAZOR_HOST_PORT}
      - CorsOrigins__1=http://${BLAZOR_CONTAINER_NAME}:${BLAZOR_CONTAINER_PORT}
    depends_on:
      linteum-db:
        condition: service_healthy
    networks:
      - linteum_prod1
    pull_policy: build

  linteum-blazor:
    build:
      context: .
      dockerfile: Linteum.BlazorApp/Dockerfile
    container_name: ${BLAZOR_CONTAINER_NAME}
    environment:
      - PASSWORD_SALT=${PASSWORD_SALT}
      - API_CONTAINER_NAME=${API_CONTAINER_NAME}
      - API_CONTAINER_PORT=${API_CONTAINER_PORT}
      - VERSION=${VERSION}
      - HUB_LINK=${HUB_LINK}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - ASPNETCORE_URLS=http://*:${BLAZOR_CONTAINER_PORT}
      - ApiBaseUrl=http://${API_CONTAINER_NAME}:${API_CONTAINER_PORT}
    ports:
      - "${BLAZOR_HOST_PORT}:${BLAZOR_CONTAINER_PORT}"
    depends_on:
      - linteum-api
    networks:
      - linteum_prod1
    pull_policy: build
    volumes:
      - blazor_keys:/app/keys

  linteum-bots:
    build:
      context: .
      dockerfile: Linteum.Bots/Dockerfile
    container_name: linteum-bots
    environment:
      - BOT_API_URL=http://${API_CONTAINER_NAME}:${API_CONTAINER_PORT}
      - BOT_TIMEOUT_MINUTES=10
    depends_on:
      - linteum-api
    networks:
      - linteum_prod1
    profiles:
      - bots
    pull_policy: build

networks:
  linteum_prod1:
    driver: bridge

volumes:
  db_data:
  blazor_keys:
